spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3307/app20230706__test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: woolocal
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none



